export const STANDARD_SEG_MAPPING: {[key: string]: string} = {
  0: 'ABCDEF',
  1: 'BC',
  2: 'ABGED',
  3: 'ABGCD',
  4: 'BCFG',
  5: 'AFGCD',
  6: 'ACDEFG',
  7: 'ABCF',
  8: 'ABCDEFG',
  9: 'ABCDFG',
  '-': 'G',
  A: 'ABCEFG',
  a: 'ABCDEG',
  B: 'CDEFG',
  C: 'DEFA',
  c: 'DEG',
  D: 'BCDEG',
  E: 'ADEFG',
  e: 'ABDEFG',
  F: 'AEFG',
  G: 'ACDEF',
  H: 'BCEFG',
  h: 'CEFG',
  i: 'C',
  J: 'BCDE',
  L: 'FED',
  n: 'CEG',
  N: 'ABCEF',
  o: 'CDEG',
  O: 'ABCDEF',
  P: 'ABEFG',
  q: 'ABCFG',
  r: 'EG',
  s: 'ACDFG',
  t: 'DEFG',
  U: 'BCDEF',
  u: 'CDE',
  V: 'BCDEF', // same as U
  v: 'CDE', // same as u
  Y: 'BEFG',
  '&o;': 'ABFG',
  '\'': 'F',
  '\"': 'BF',
  _: 'D',
  '=': 'DG',
  '[': 'ADEF',
  ']': 'ABCD',
  ';': ':.,',
  ',': '.,',
  '.': '.',
  ':': ':.',
  ' ': ''
};
